{% set version = "0.13.5" %}

package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glymur/Glymur-{{ version }}.tar.gz
  sha256: 41c826b7b5900df9485a887d67bf93dfb9695e78d653feb1646ff994769116b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - numpy
    - lxml
    - openjpeg >=2.1.1
    - packaging

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib

  commands:
    - python -c "import glymur; j = glymur.Jp2k(glymur.data.nemo()); print(j)"
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  license_file: LICENSE.txt
  summary: Tools for accessing JPEG2000 files

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
