{% set version = "0.9.1" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glymur/Glymur-{{ version }}.tar.gz
  sha256: 034d897dffa9a00a8a5b751f581d162381a4089f72ae3430e1f059913a993547

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - lxml
    - mock
    - contextlib2

  run:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4
    - openjpeg >=2.1.1

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib

  commands:
    - python -c "import glymur; j = glymur.Jp2k(glymur.data.nemo()); print(j)"
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  license_file: LICENSE.txt
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
