{% set version = "0.8.15" %}
package:
  name: glymur
  version: {{ version }}

source:
  fn: Glymur-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glymur/Glymur-{{ version }}.tar.gz
  sha256: 006ec841ec8782a0d5b7128499d30bdacd33397b9005bbb16b6b14dc8a8f25a6

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jp2dump=glymur.command_line:main

requirements:
  build:
    - python
    - setuptools
    - numpy
    - lxml
    - mock
    - contextlib2

  run:
    - python
    - setuptools
    - numpy >=1.7.0
    - lxml >=2.3.2
    - contextlib2 >=0.4
    - openjpeg >=2.1.1

test:
  # Python imports
  imports:
    - glymur
    - glymur.data
    - glymur.lib

  commands:
    - python -c "import glymur; j = glymur.Jp2k(glymur.data.nemo()); print(j)"
    - jp2dump --help

about:
  home: https://github.com/quintusdias/glymur
  license: MIT
  summary: 'Tools for accessing JPEG2000 files'

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - quintusdias
