travis:
  secure:
    BINSTAR_TOKEN: Ve2jamTNfDH77R2jQzPSJn7wEe/JtrbrIS5HCsXXucWCNkjfyRHQnN2VjckvaH/bN0ocffx+K3PCo+6O49ooi2Rr1ZCoaChFw0sJC400BPBQvoUkMXhkrtUinEUxrpTUhN4mm8RHrL3dHzO4HfLCBngH5zCJX0IBnbOzrsLViP6mtt2hCrNZpQ/WlFvVebBex7qgK+aP1XWcpMNqYcQbj5nZlTv4O2IHU+4duDi8al05vG3YTper+Vi7XcWk5QkMQnMmIn6Wne0RbGlO7GKplPogSeLCgqju3RZb+2BCe0a5tAP7tha3L2t6Y6A2P4JBs36jooEW+e0RE2J2TdeHT3hKrMeaEXV2GiWAvUcWNBaeIfBgUrPx5pUI2VullT/5pQBLn4WBXakpKlxCq73LfNp2rpBkgCNX9JGl9rpOAbHuuYiGwSHzFtKzoUUg66Z+soBIZU8KiEjlOOuJgjnTHJChmhzd7RL1OHgxcLuK8e3FbcXkQO/fkiSIbKCE2Uiik073qwU1xKmh1FGQNSd84pj39pl70EDifbsGQeUcRAtXCz4EYcsm35Jn410+MAupW1Eec/Nl6AmtjbnqYHY632PVP5ZD+Nj8+tZ7s75AoAcxwuoaKtx9kXchudYy+repSrL6h7eOID1SnUDMlawOftTrEJHq8Mprv18o1/vNwcg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
