travis:
  secure:
    BINSTAR_TOKEN: O7d+10qhdP97LBcWpYKtLdZcWhKp2CCIAZyd0xAB9HCH02OCJ3GnIGSxefroZQGJZ83rlZy4e34ZpQ6JTLzNiOScoxsJeKHqmIOMZ7vCfWNUj6USpxhGf4sU2SfLBGbc6F5hKTxQ08j86nAsfN3Lt/bFYf6OpB656zFji4WAhPhUpPNGSA6mwrvTUR5/+bApDj4l3jIH9UlYVAlp9HG0rmtxECDrUbKZXsJhy0VMycX2uFqvOa1qKhTMAHe8/t5woyiQAeZ9uvDw0sXfkYSO97ROUPgB+2xbHWKjXnuOFAGGXgXMAuVslkETN7RdYyXu0hTsQsudzMSLxcNV8BNIR8PajF6X1ViUsl6ShK13ebumV1SW3opjg4YwITOIvydfF05HhEvxjMJDbvpKH2/VsxVjN8GWUwEyzwQjxc2u2wQeqPox89D19e2btte9CeWp2QeX9C/x384eFrSJayleqV65Ks5KK7VDNYsnpu7XrSnQ59B+JWARhEY+3B+LD4N9FbLyK13gswP4Ry7mb2HBB0HHf2bMQR/BxJtx9liPaa1U+K7NlzZsARpadAdkT/tMonJ/YqkqcUmAzHrUVZMH3C5Fe5IY4cpTKQlj0YO7u3GICka4pLcllQvfpMwYhpnRxeZgKJK6n5nippeB2RcQxmQFFBVcUVbU6pEUXeYLXkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
